name: Deploy with Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and run app
        run: |
          go build -o Receiver-APP
          sudo pkill -f Example_interface || true
          nohup ./Receiver-APP > app.log 2>&1 &
